### ISSUE TITLE
Website 404 error 

### ISSUE THREAD

**Issue by ulubis** [0xvashishth/CalcHub#389]
Hi, 

I am reporting that the website is returning 404 error

Here's the screen picture

![Screenshot_20240502_094412_Chrome](https://github.com/0xvashishth/CalcHub/assets/157541760/fd165ae0-1a8c-4114-ab32-86388fa704b2)

**Comment by 0xvashishth** [comment]
Hey Thanks for pointing it out.
here's the new website link that you can try: https://0xvashishth.github.io/CalcHub
